[[constraint]]
  name = "cloud.google.com/go"
  version = "0.10.0"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/configfile"

[[constraint]]
  name = "github.com/acoshift/go-firebase-admin"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/header"

[[constraint]]
  name = "github.com/acoshift/middleware"
  version = "0.2.0"

[[constraint]]
  name = "github.com/acoshift/hime"
  version = "0.0.18"

[[constraint]]
  name = "github.com/acoshift/session"
  version = "0.6.0"

[[constraint]]
  name = "github.com/acoshift/methodmux"
  version = "1.0.0"

[[constraint]]
  name = "github.com/acoshift/prefixhandler"
  version = "1.0.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "6.0.0"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
