
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "cloud.google.com/go"
  version = "0.10.0"

[[constraint]]
  name = "github.com/acoshift/cachestatic"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/configfile"

[[constraint]]
  name = "github.com/acoshift/flash"
  version = "0.0.1"

[[constraint]]
  name = "github.com/acoshift/go-firebase-admin"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/header"

[[constraint]]
  name = "github.com/acoshift/middleware"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/acoshift/servertiming"

[[constraint]]
  name = "github.com/acoshift/session"
  version = "0.1.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "6.0.0"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.4.0"

[[constraint]]
  name = "github.com/tdewolff/minify"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
